### ISSUE TITLE
Not able to create user using POSTMAN

### ISSUE THREAD

**Issue by trinidado007** [epignosis/efrontPRO-SDK#15]
Hi there,
     I am testing my eFront environment using POSTMAN. The GET method just works fine, but the POST doesn't seem to be working. the final URL before send looks like this:

http://XXXXX.demo.efrontlearning.com/API/v1.0/User?login=test@gmail.com&name=test&surname=test&email=test@gmail.com&password=testttTRTR
This below is the error i am getting : 
{
  "error": {
    "code": 400,
    "message": "Not possible to create the user.",
    "reason": "login, name, surname, email and password are required."
  },

And if i change the URL to this (putting / before ? ):

http://XXXXX.demo.efrontlearning.com/API/v1.0/User?login=test@gmail.com&name=test&surname=test&email=test@gmail.com&password=testttTRTR

This is the error i am getting : 
{
  "error": {
    "code": 404,
    "message": "The requested API call is unknown. Please read the API documentation."
  },
  "executionDuration": 0.0021,
  "success": false,
  "version": "1.0"
}

Please Help

**Comment by razorfish79** [comment]
As it is a POST it does work different than a GET and you cannot send the variables through the URL.
You need to write it into the body of the request. The API itself works just fine.

![image](https://cloud.githubusercontent.com/assets/3584214/26388529/1b986e78-4055-11e7-8ff8-6f77e0791e12.png)

**Comment by trinidado007** [comment]
Thank you Sir,
                     It is all work fine when using the body for the request.
Really appreciate your  help. :)
