### ISSUE TITLE
How to update User_Type_Id and User_type_name

### ISSUE THREAD

**Issue by thatoneitchick** [epignosis/efrontPRO-SDK#23]
I tried updating these with the /User/ID PUT call, but this did not work. Is there a call specifically for changing a user's User Type? 

These are different than group and job, and pertain to the User's level of access in the system. 

Thanks!

**Comment by xarhsdev** [comment]
Hi @thatoneitchick 

No there is not, but I can add this functionality along with an API call, to return the list of the available user types.

**Comment by thatoneitchick** [comment]
That would be great, as we are creating an integration between our HR software and LMS and need to be able to edit this when new users are created in Efront.

Thank you!

**Comment by xarhsdev** [comment]
We draft a new release approximately every 2 weeks, and both, will be included in our latest version.

**Comment by thatoneitchick** [comment]
@xarhsdev I see how to view user-types in the documentation, but not how to update a User's user type.

**Comment by xarhsdev** [comment]
@thatoneitchick 

1. You will need, eFront v5.1.8 which is unreleased yet (probably today or tomorrow). 
1. You will need, eFront SDK v[3.2.0](https://github.com/epignosis/efrontPRO-SDK/releases/tag/v3.2.0).

### Examples
```php
use Epignosis\eFrontPro\Sdk\Factory\Handler\API;
use Epignosis\eFrontPro\Sdk\Request\Handler\cURL;
use Epignosis\eFrontPro\Sdk\eFrontProSDK;

require 'Source\AutoLoader.php';

try {
    // Setup SDK:
    $sdk = new eFrontProSDK(new API(new cURL));
    $sdk->Config('1.0' , 'your_domain_goes_here', 'api_key_goes_here');

    // Return information for any available user type:
    $response[] = $sdk->GetAPI('UserTypeList')->GetAll();

    // Return information about user type with id=16:
    $response[] = $sdk->GetAPI('UserType')->GetInfo(16);

    // Update user:
    $response[] = $sdk->GetAPI('User')->Edit(19, ['user_types_ID' => 8]);

    // Create user:
    $response[] = $sdk->GetAPI('User')->Create ([
        'login' => 'xdev',
        'name' => 'X',
        'surname' => 'D',
        'email' => 'xarhsdev@efrontlearning.com',
        'password' => 'password',
        'user_types_ID' => 1
    ]);

    // Print responses ..
    // ..
} catch (\Exception $throwable) {
    print_r($throwable);
}
```
