### ISSUE TITLE
Missing skills in user info

### ISSUE THREAD

**Issue by razorfish79** [epignosis/efrontPRO-SDK#25]
I would be great if the user info also would contain the gained skills and skill info (score, related course, ...) of a user as the report/export functionality inside efront pro for skills isn´t that usefull.

plus add skill (skill ID or somewhat) to user via API

**Comment by xarhsdev** [comment]
Hi @razorfish79 

we can add this information in /User/:Id API call. I'll let you know when it's complete.

**Comment by razorfish79** [comment]
That would be really awesome. Thank you so much.

**Comment by razorfish79** [comment]
@xarhsdev 
I am pretty impressed!!!!!
Thank you.

**Comment by xarhsdev** [comment]
Issue solved :)
