### ISSUE TITLE
Unclear documentation, missing examples

### ISSUE THREAD

**Issue by BerndGewehr** [epignosis/efrontPRO-SDK#28]
Hi!

Can you give some more examples on how to use the REST api calls correctly?

Does 
```
/CourseUserStatus/:CourseId,:UserId
```
mean
```
/CourseUserStatus/:182,:36
```
or
```
/CourseUserStatus/182,36
```
or something else?
I get resultcode 400 whatever I try.......

```
"{"error":{"code":400,"message":"An unexpected error occurred.","reason":"Ung\u00fcltige ID: "}
```

**Comment by xarhsdev** [comment]
Hi @BerndGewehr 

The correct API call, is: `/CourseUserStatus/182,36`.

**Comment by BerndGewehr** [comment]
If the docs would contain some more examples, the start experience for a new developer would surely be much better. Anyway, good work! Helped me a lot to automate stuff with node red via the eFront API.
