### ISSUE TITLE
Missing API "Get assigned users to a course"

### ISSUE THREAD

**Issue by BerndGewehr** [epignosis/efrontPRO-SDK#29]
We would like to have a REST api for assigned users of a course for automatic access to a discussion space in another system.

Can you add that one?

```
/Course/:courseID/users
```
for example...

**Comment by xarhsdev** [comment]
Hi @BerndGewehr 

can you explain a more about the use case? 

`/Course/:courseID`, already returns the list of assigned users.

**Comment by BerndGewehr** [comment]
Understood.
 
I now found a way using that api endpoint to fulfill my request.
 
All assigned people from a course now get automatically added to the course room by using a node-red flow.
 
Thank you for helping me with that.Mit freundlichen Grüßeni. A.Bernd GewehrLeiter Informationstechnik
Vössing Ingenieurgesellschaft mbHBrunnenstr. 1140223 DüsseldorfTel: +49 211 93449-0Mobil: +49 1520 9328236Fax: +49 211 93449-59Mail: Bernd.Gewehr@voessing.deWeb: www.voessing.de
 
 
--
Firmensitz/Headoffice:Voessing Ingenieurgesellschaft mbH DuesseldorfDeutschland
Internet: http://www.voessing.de
Geschaeftsfuehrer/Managing Directors:Dipl.-Ing. Heiko BorchardtDipl.-Ing. Rudolf Vienenkoetter
Handelsregister/Commercial registryAmtsgericht Duesseldorf, HRB 54709
USt-Ident-Nr.: DE 121641768----- Original message -----From: xarhsdev <notifications@github.com>To: epignosis/efrontPRO-SDK <efrontPRO-SDK@noreply.github.com>Cc: Bernd Gewehr <bernd.gewehr@voessing.de>, Mention <mention@noreply.github.com>Subject: Re: [epignosis/efrontPRO-SDK] Missing API "Get assigned users to a course" (#29)Date: Fri, Oct 26, 2018 9:51 AM 
Hi @BerndGewehr
can you explain a more about the use case?
/Course/:courseID, already returns the list of assigned users.
