### ISSUE TITLE
Is there an API to request tests?

### ISSUE THREAD

**Issue by BerndGewehr** [epignosis/efrontPRO-SDK#32]
Like in the reports for specific tests, we would like to be able to request the current result of a test for all users via a REST endpoint. The course does not apply the changed result of a repeated test for some reason that's why we try to read the current result over the API.

/tests/{id}/users

would be fine as a list of users with the results like in the report:
https://training.voessing.de/reports/op/tests/test-id/52

**Comment by pvenakis** [comment]
Hello @BerndGewehr, when you say that "The course does not apply the changed result of a repeated test", can you elaborate? Do you meant that, for a completed course, if the test is resubmitted, the course's score does not change to reflect the new test score?

**Comment by BerndGewehr** [comment]
Yes, that's what we see. You have to click on a "recalculate score" button in each course for the repeated tests to apply to the course scoring results.

**Comment by BerndGewehr** [comment]
![image](https://user-images.githubusercontent.com/21081707/56586687-72866200-65e0-11e9-9aed-ae464f06752b.png)

**Comment by pvenakis** [comment]
you will be happy to know then that we have just introduced a new feature, called "scoring behaviour" that allows you to define whether and how a complete course's score follows changes in the score of its contents. This feature will appear on your portal in the next few days.

**Comment by BerndGewehr** [comment]
@pvenakis can you confirm that this change was made? Where in the settings of a course can I find that setting?

**Comment by pvenakis** [comment]
@BerndGewehr it will be rolled out to all of our customers tonight, so look for it tomorrow, under the "course rules" section

**Comment by BerndGewehr** [comment]
Great.

Which of the option is the right one?
![image](https://user-images.githubusercontent.com/21081707/57294964-927e5100-70c9-11e9-8641-26c35fa5b301.png)

**Comment by pvenakis** [comment]
@BerndGewehr I apologize for this, but the feature roll out has been delayed for a couple of days due to QA findings. If you can't wait, we can push it to your installation directly

**Comment by BerndGewehr** [comment]
We prefer to wait until QA is finished. TY!
