### ISSUE TITLE
Add user to a Branch or Group fails

### ISSUE THREAD

**Issue by bniesen** [epignosis/efrontPRO-SDK#33]
Adding a user to group or branch crashes with error code 400, invalid id.
I am sure the id`s are correct. 
A group with id 18 exists, also a branch with id 2 and a user with userid 978.

Post request, form-urlencoded:
https://training.portal.de/API/v1.0/Group/18/AddUser?userId=978
https://training.portal.de/API/v1.0/Branch/2/AddUser?userId=978

Result:
{
    "error": {
        "code": 400,
        "message": "Not possible to add the requested user to the requested group.",
        "reason": "Ungültige ID: "
    },
    "executionDuration": 0.0029,
    "success": false,
    "version": "1.0"
}

**Comment by xarhsdev** [comment]
Hi @bniesen 

| Method | Endpoint | Body Encoding | Body Parameter Names |
|:---:|:---|:---:|:---:|
| POST | /API/v1.0/Branch/AddUser | form-data | BranchId, UserId |
| POST | /API/v1.0/Group/AddUser | form-data | GroupId, UserId |

**Comment by bniesen** [comment]
Same result:
https://......./API/v1.0/Branch/AddUser?branchid=2&userId=1019
https://......./API/v1.0/Group/AddUser?groupid=18&userId=1019

{
    "error": {
        "code": 400,
        "message": "Not possible to add the requested user to the requested branch.",
        "reason": "Ungültige ID: "
    },
    "executionDuration": 0.0027,
    "success": false,
    "version": "1.0"
}

**Comment by xarhsdev** [comment]
[GET] parameters `branchid`, `groupid` and `userId` are not valid. These parameters should be sent as follows:

```curl
curl -X POST \
  http://127.0.0.1/API/v1.0/Group/AddUser \
  -H 'Authorization: Basic NWU4NjdlOTAxNWJhYjUzMWUyNjg6' \
  -H 'Content-Length: 269' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F GroupId=1 \
  -F UserId=3
```

```
POST /API/v1.0/Group/AddUser HTTP/1.1
Host: 127.0.0.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Basic NWU4NjdlOTAxNWJhYjUzMWUyNjg6
Content-Length: 269


Content-Disposition: form-data; name="GroupId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW--,
Content-Disposition: form-data; name="GroupId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW--
Content-Disposition: form-data; name="UserId"

3
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Comment by bniesen** [comment]
Yes, sure. I do a post request. User creation and editing works by the way.
