### ISSUE TITLE
Add Users to Courses

### ISSUE THREAD

**Issue by Reiner-Browning** [epignosis/efrontPRO-SDK#34]
Hoping someone can help - I've been using the efrontPRO API for DHX LMS... 

Managed to figure everything out except for adding a user to a Course. In the API Documentation, it states to put the user's ID in the "PUT field", but not really specifying what that means. I've been able to update a user's profile with a PUT request ('x-www-form-urlencoded') and key value pairs, but unable to use PUT for /Course/:Id/AddUser

What am I doing wrong?

**Comment by Rei-Ai** [comment]
Figured it out after reading someone's issue with adding a user to a group.
Key to use is 'UserId' and set 'Force' to 'true'
